export const SIGN_IN = "SIGN_IN";

export const LOGIN = "LOGIN";
export const ERROR_LOGIN = "ERROR_LOGIN";
export const REGISTER = "REGISTER";
export const LOGOUT = "LOGOUT";
export const UPDATE_JWT = "UPDATE_JWT";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const ALL_PRODUCTS = "ALL_PRODUCTS";
export const ERROR_ALL_PRODUCTS = "ERROR_ALL_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const ERROR_CREATE_PRODUCT = "ERROR_CREATE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const ERROR_UPDATE_PRODUCT = "ERROR_UPDATE_PRODUCT";
export const SET_INITIAL_UPDATE = "SET_INITIAL_UPDATE";
export const ERROR_SET_INITIAL_UPDATE = "ERROR_SET_INITIAL_UPDATE";
export const GET_INITIAL_UPDATE = "GET_INITIAL_UPDATE";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ERROR_DELETE_PRODUCT = "ERROR_DELETE_PRODUCT";
export const SET_CURRENT_DELETE = "SET_CURRENT_DELETE";
export const GET_PRODUCT = "GET_PRODUCT";
export const SET_PRODUCT = "SET_PRODUCT";
export const ERROR_SET_PRODUCT = "ERROR_SET_PRODUCT";
export const CLEAR_MODAL = "CLEAR_MODAL";
export const UPDATE_FILTERS = "UPDATE_FILTERS";

export const GET_BRANDS = "GET_BRANDS";
export const ALL_BRANDS = "ALL_BRANDS";
export const ERROR_ALL_BRANDS = "ERROR_ALL_BRANDS";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const ALL_CATEGORIES = "ALL_CATEGORIES";
export const ERROR_ALL_CATEGORIES = "ERROR_ALL_CATEGORIES";

export const API = "API";
export const API_START = "API_START";
export const API_END = "API_END";
export const API_ERROR = "API_ERROR";

export const NOTIFICATION = "NOTIFICATION";
